AP_Periph: correct function name for detected protocol name
 ../../Tools/AP_Periph/rc_in.cpp: In member function 'void AP_Periph_FW::rcin_update()':
../../Tools/AP_Periph/rc_in.cpp:117:31: error: 'class AP_RCProtocol' has no member named 'protocol_name'; did you mean 'protocol_enabled'?
  117 |     auto new_rc_protocol = rc.protocol_name();
      |                               ^~~~~~~~~~~~~
      |                               protocol_enabled
compilation terminated due to -Wfatal-errors.