AP_InternalError: added invalid_arguments failure
this is intended to catch problems where we have unexpectedly received
invalid arguments.  For example an out-of-bounds target speed that
should have been caught somewhere else.

running out of bits so we use a single bit to capture invalid inputs to or output from a calculation