github: remove elf_diff from checks we run
We had previous discussed removing this as it was very-little-used.

Today this workflow died because elf_diff failed to install:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/elf_diff/__main__.py", line 23, in <module>
    from elf_diff.pair_report_document import generateDocument, ValueTreeNode
  File "/usr/local/lib/python3.8/dist-packages/elf_diff/pair_report_document.py", line 34, in <module>
    import elf_diff.binary as binary
  File "/usr/local/lib/python3.8/dist-packages/elf_diff/binary.py", line 27, in <module>
    from elf_diff.instruction_collector import InstructionCollector
  File "/usr/local/lib/python3.8/dist-packages/elf_diff/instruction_collector.py", line 28, in <module>
    import progressbar  # type: ignore # Make mypy ignore this module
  File "/usr/local/lib/python3.8/dist-packages/progressbar/__init__.py", line 5, in <module>
    from .bar import DataTransferBar
  File "/usr/local/lib/python3.8/dist-packages/progressbar/bar.py", line 13, in <module>
    from python_utils import types
  File "/usr/local/lib/python3.8/dist-packages/python_utils/__init__.py", line 1, in <module>
    from . import (
  File "/usr/local/lib/python3.8/dist-packages/python_utils/aio.py", line 8, in <module>
    from . import types
  File "/usr/local/lib/python3.8/dist-packages/python_utils/types.py", line 4, in <module>
    from typing_extensions import *  # type: ignore  # noqa: F403
ModuleNotFoundError: No module named 'typing_extensions'