AP_MSP: correct compilation when GPS disabled
../../libraries/AP_MSP/AP_MSP_Telem_Backend.cpp: In member function 'virtual void AP_MSP_Telem_Backend::update_gps_state(AP_MSP_Telem_Backend::gps_state_t&)':
../../libraries/AP_MSP/AP_MSP_Telem_Backend.cpp:206:5: error: 'AP_GPS' was not declared in this scope; did you mean 'RAW_GPS'?
  206 |     AP_GPS& gps = AP::gps();
      |     ^~~~~~
      |     RAW_GPS
compilation terminated due to -Wfatal-errors.